export const DSGNERS_SAMPLE_URLS = [
  "https://dsgners.ru/avito/11995-5-zadach-kotoryie-ux-issledovateli-avito-reshayut-s-pomoschyu-neyrosetey",
  "https://dsgners.ru/b2bdesign/11762-kak-uluchshit-ux-v-1s-ne-perepisyivaya-kod",
  "https://dsgners.ru/theburmistrov/11415-figma-dobavila-effekt-stekla-kak-na-ios-26",
  "https://dsgners.ru/orshakserg/11524-figma-variables-kak-polzovatsya-peremennymi-i-tokenami",
  "https://dsgners.ru/evgeniashamray/11254-kak-ya-proveryayu-ux-formyi-s-pomoschyu-neyroseti",
  "https://dsgners.ru/proddesiign/11330-emotsionalnyiy-ux-na-vseh-etapah-razrabotki-tsifrovogo-produkta-ot-issledovaniy-do-mikrovzaimodeystviy",
  "https://dsgners.ru/proddesiign/11859-evristiki-ux-fundament-dlya-uspeshnogo-tsifrovogo-produkta",
  "https://dsgners.ru/cherkasov_uxui/11804-pochemu-v-interfeysah-so-slojnoy-logikoy-nedostatochno-pokazat-maketyi-v-figma",
  "https://dsgners.ru/na_produkte/11155-5-prichin-pochemu-dizayneru-stoit-idti-rabotat-v-b2b",
  "https://dsgners.ru/theburmistrov/11801-ii-generator-interfeysov-ot-figma-vyishel-v-otkryityiy-dostup",
  "https://dsgners.ru/cherkasov_uxui/11810-pixso-eto-novaya-figma-ili-god-stradaniy",
  "https://dsgners.ru/designslot/11226-11-tehnik-ii-kotoryie-ekonomyat-vremya-produktovomu-dizayneru",
  "https://dsgners.ru/evgeniashamray/11762-kak-uluchshit-ux-v-1s-ne-perepisyivaya-kod",
  "https://dsgners.ru/atwinta/11415-figma-dobavila-effekt-stekla-kak-na-ios-26",
  "https://dsgners.ru/atwinta/11796-teper-steklyannyim-budet-vsjo-apple-vyipustila-beta-versiyu-interfeysa-so-steklom-a-figma-uje-dobavili-etot-instrument-v-svoy-funktsional",
  "https://dsgners.ru/proddesiign/11859-evristiki-ux-fundament-dlya-uspeshnogo-tsifrovogo-produkta",
  "https://dsgners.ru/cherkasov_uxui/11847-lektoriy-dprofile-v-saratove",
  "https://dsgners.ru/azagency.design/11850-sistemnyie-prodaji-v-agentstve-mif-ili-realnost",
  "https://dsgners.ru/avito/11163-kak-ya-delal-testovyie-v-techenie-10-let-chto-ponyal-i-pochemu-oni-ne-ravnyi-vaytbordam",
  "https://dsgners.ru/golfui/42981-vovlechjonnost-nachinaetsya-s-kontenta-ot-statichnogo-sayta-k-jivomu-obscheniyu",
  "https://dsgners.ru/tiho.design/42992-fokus-samyiy-ogranichennyiy-resurs-o-kotorom-pochti-nikto-ne-govorit",
];

